### PR TITLE
Added beta site banner

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
@n1hility banner announcing the beta site

**Comment by jkbrock** [comment]
@n1hility @jmesnil @dmlloyd @jamezp 

Any thoughts on this addition?

**Comment by jamezp** [comment]
I think it looks fine, but I think @n1hility needs to make the call. 

I did notice a couple changes that should be made on the beta site. Specifically the download links should link to 14.0.1 and there is no 14 listed on the downloads page.

**Comment by bstansberry** [comment]
I rebased this and sent up #114, which is merged.

Sorry I didn't merge this earlier; I didn't realize the beta site had moved to referencing WF 15.

Note that 16 will be out by the end of the week.

**Pull request closed without merging**
