### PR TITLE
Add a blog post link about dynamic client SSL context

### PR DESCRIPTION
**Pull request by Skyllarr**

### CODE REVIEW

**Comment by Skyllarr** [comment]
@fjuma Please review, thank you!

**Comment by fjuma** [comment]
@Skyllarr Thanks, looks good! Please add a summary at the bottom as mentioned here:

https://github.com/wildfly/wildfly.org/pull/608#issuecomment-2098418174

**Comment by Skyllarr** [comment]
Thank you @fjuma ! I added a quick summary

**Comment by bstansberry** [comment]
Thanks @Skyllarr and @fjuma

**Pull request merged**
