### PR TITLE
[WFLY-3014] : Adding all the xsds from wildfly schema folder with glorious index page.

### PR DESCRIPTION
**Pull request by ehsavoie**
Ok it's awful but it is a simple solution to expose all those schema that are desperately needed if we want to be able to validate the XML from external tools (who said IDE).

### CODE REVIEW

**Comment by rhusar** [comment]
So why should the schemas be here on wildfly.org if we host them (officially) on http://www.jboss.org/schema/jbossas/ ? Seems like unncessary confusion to me at this point.

**Comment by ehsavoie** [comment]
Because those are not as easy to maintain : currently WildFly 9 schemas are not available there :(

**Comment by rhusar** [comment]
Sounds more like a process problem to me. Same way someone has to do an SCP to there, someone has to build and publish this website (plus the extra commit, pull request, merge).

**Comment by n1hility** [comment]
Yeah I agree that we need a process first before we make it worse. I wonder if maybe we should just have a bunch of links to github repo locations, and then the updates come in automatically?

**Pull request closed without merging**
