### PR TITLE
Add post link: Introducing The Java Batch Processing API And JBeret Implementation

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Review by bstansberry — CHANGES_REQUESTED** [review]
This works great @liweinan 

Please also add changes equivalent to https://github.com/wildfly/wildfly.org/pull/381/files for yourself. The authors.yaml entry results in your proper name appearing in the post and on the news page. As discussed on https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/Blog.20post.20author.20pictures the picture doesn't currently do anything, but that may change, so unless you don't want a picture it's good to have one in the repo.

**Comment by bstansberry** [comment]
BTW I just experimented with putting 汉子 in the value for "name" in authors.yaml and they render properly on the "news" page. So if you want to also include 利阿男that will work fine.

**Comment by liweinan** [comment]
@bstansberry yes sir!

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @liweinan

**Pull request merged**
