### PR TITLE
Blog post about the GraphQL feature pack

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Comment by jmartisk** [comment]
@phillip-kruger, @kabir

**Comment by jmartisk** [comment]
I'm leaving for a longer PTO in a few hours so if changes are needed, feel free to do them for me

**Comment by kabir** [comment]
@phillip-kruger I guess @jmartisk would want us to publish this now rather than waiting for him to come back? If so, @jamezp knows how to publish this.

**Comment by phillip-kruger** [comment]
Yes please !!

**Pull request merged**
